//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiThuVienEntities : DbContext
    {
        public QuanLiThuVienEntities()
            : base("name=QuanLiThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DbSet<ChiTietPhieuTra> ChiTietPhieuTras { get; set; }
        public virtual DbSet<DauSach> DauSaches { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<LoaiSach> LoaiSaches { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuTra> PhieuTras { get; set; }
        public virtual DbSet<QuanTri> QuanTris { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
    
        public virtual int NhapChiTietPhieuMuon(Nullable<long> iD_PhieuMuon, Nullable<long> iD_DauSach, Nullable<long> iD_Sach, Nullable<double> soluong)
        {
            var iD_PhieuMuonParameter = iD_PhieuMuon.HasValue ?
                new ObjectParameter("ID_PhieuMuon", iD_PhieuMuon) :
                new ObjectParameter("ID_PhieuMuon", typeof(long));
    
            var iD_DauSachParameter = iD_DauSach.HasValue ?
                new ObjectParameter("ID_DauSach", iD_DauSach) :
                new ObjectParameter("ID_DauSach", typeof(long));
    
            var iD_SachParameter = iD_Sach.HasValue ?
                new ObjectParameter("ID_Sach", iD_Sach) :
                new ObjectParameter("ID_Sach", typeof(long));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapChiTietPhieuMuon", iD_PhieuMuonParameter, iD_DauSachParameter, iD_SachParameter, soluongParameter);
        }
    
        public virtual int NhapChiTietPhieuTra(Nullable<long> iD_PhieuTra, Nullable<long> iD_DauSach, Nullable<double> soluong, Nullable<long> iD_Sach)
        {
            var iD_PhieuTraParameter = iD_PhieuTra.HasValue ?
                new ObjectParameter("ID_PhieuTra", iD_PhieuTra) :
                new ObjectParameter("ID_PhieuTra", typeof(long));
    
            var iD_DauSachParameter = iD_DauSach.HasValue ?
                new ObjectParameter("ID_DauSach", iD_DauSach) :
                new ObjectParameter("ID_DauSach", typeof(long));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(double));
    
            var iD_SachParameter = iD_Sach.HasValue ?
                new ObjectParameter("ID_Sach", iD_Sach) :
                new ObjectParameter("ID_Sach", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapChiTietPhieuTra", iD_PhieuTraParameter, iD_DauSachParameter, soluongParameter, iD_SachParameter);
        }
    
        public virtual int NhapPhieuTra(string iD_DocGia, string iD_NguoiDung, string ngayTra)
        {
            var iD_DocGiaParameter = iD_DocGia != null ?
                new ObjectParameter("ID_DocGia", iD_DocGia) :
                new ObjectParameter("ID_DocGia", typeof(string));
    
            var iD_NguoiDungParameter = iD_NguoiDung != null ?
                new ObjectParameter("ID_NguoiDung", iD_NguoiDung) :
                new ObjectParameter("ID_NguoiDung", typeof(string));
    
            var ngayTraParameter = ngayTra != null ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapPhieuTra", iD_DocGiaParameter, iD_NguoiDungParameter, ngayTraParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachSachMuon_Result> sp_DanhSachSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSachMuon_Result>("sp_DanhSachSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongDauSach_Result> sp_SoLuongDauSach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongDauSach_Result>("sp_SoLuongDauSach");
        }
    
        public virtual ObjectResult<sp_SoLuongMuon_Result> sp_SoLuongMuon(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongMuon_Result>("sp_SoLuongMuon", ngayParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_SoLuongSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_SoLuongSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongTra_Result> sp_SoLuongTra(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongTra_Result>("sp_SoLuongTra", ngayParameter);
        }
    }
}
