//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiThuViendb : DbContext
    {
        public QuanLiThuViendb()
            : base("name=QuanLiThuViendb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DbSet<ChiTietPhieuTra> ChiTietPhieuTras { get; set; }
        public virtual DbSet<DauSach> DauSaches { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<LoaiSach> LoaiSaches { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuTra> PhieuTras { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
    
        public virtual int NhapChiTietPhieuMuon(Nullable<long> iD_PhieuMuon, Nullable<long> iD_DauSach, Nullable<long> iD_Sach, Nullable<double> soluong)
        {
            var iD_PhieuMuonParameter = iD_PhieuMuon.HasValue ?
                new ObjectParameter("ID_PhieuMuon", iD_PhieuMuon) :
                new ObjectParameter("ID_PhieuMuon", typeof(long));
    
            var iD_DauSachParameter = iD_DauSach.HasValue ?
                new ObjectParameter("ID_DauSach", iD_DauSach) :
                new ObjectParameter("ID_DauSach", typeof(long));
    
            var iD_SachParameter = iD_Sach.HasValue ?
                new ObjectParameter("ID_Sach", iD_Sach) :
                new ObjectParameter("ID_Sach", typeof(long));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapChiTietPhieuMuon", iD_PhieuMuonParameter, iD_DauSachParameter, iD_SachParameter, soluongParameter);
        }
    
        public virtual int NhapChiTietPhieuTra(Nullable<long> iD_PhieuTra, Nullable<long> iD_DauSach, Nullable<double> soluong, Nullable<long> iD_Sach)
        {
            var iD_PhieuTraParameter = iD_PhieuTra.HasValue ?
                new ObjectParameter("ID_PhieuTra", iD_PhieuTra) :
                new ObjectParameter("ID_PhieuTra", typeof(long));
    
            var iD_DauSachParameter = iD_DauSach.HasValue ?
                new ObjectParameter("ID_DauSach", iD_DauSach) :
                new ObjectParameter("ID_DauSach", typeof(long));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(double));
    
            var iD_SachParameter = iD_Sach.HasValue ?
                new ObjectParameter("ID_Sach", iD_Sach) :
                new ObjectParameter("ID_Sach", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapChiTietPhieuTra", iD_PhieuTraParameter, iD_DauSachParameter, soluongParameter, iD_SachParameter);
        }
    
        public virtual int NhapPhieuMuon(string iD_DocGia, string ngayMuon, string ngaygioihantra)
        {
            var iD_DocGiaParameter = iD_DocGia != null ?
                new ObjectParameter("ID_DocGia", iD_DocGia) :
                new ObjectParameter("ID_DocGia", typeof(string));
    
            var ngayMuonParameter = ngayMuon != null ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(string));
    
            var ngaygioihantraParameter = ngaygioihantra != null ?
                new ObjectParameter("ngaygioihantra", ngaygioihantra) :
                new ObjectParameter("ngaygioihantra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapPhieuMuon", iD_DocGiaParameter, ngayMuonParameter, ngaygioihantraParameter);
        }
    
        public virtual int NhapPhieuTra(string iD_DocGia, string ngayTra)
        {
            var iD_DocGiaParameter = iD_DocGia != null ?
                new ObjectParameter("ID_DocGia", iD_DocGia) :
                new ObjectParameter("ID_DocGia", typeof(string));
    
            var ngayTraParameter = ngayTra != null ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapPhieuTra", iD_DocGiaParameter, ngayTraParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachSachMuon_Result> sp_DanhSachSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSachMuon_Result>("sp_DanhSachSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongDauSach_Result> sp_SoLuongDauSach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongDauSach_Result>("sp_SoLuongDauSach");
        }
    
        public virtual ObjectResult<sp_SoLuongMuon_Result> sp_SoLuongMuon(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongMuon_Result>("sp_SoLuongMuon", ngayParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongSachMuon_Result> sp_SoLuongSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongSachMuon_Result>("sp_SoLuongSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongTra_Result> sp_SoLuongTra(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongTra_Result>("sp_SoLuongTra", ngayParameter);
        }
    
        public virtual ObjectResult<sp_thongtindocgia_Result> sp_thongtindocgia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_thongtindocgia_Result>("sp_thongtindocgia");
        }
    
        public virtual ObjectResult<sp_thongtinsach_Result> sp_thongtinsach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_thongtinsach_Result>("sp_thongtinsach");
        }
    
        public virtual ObjectResult<sp_timkiemdocgia_Result> sp_timkiemdocgia(string tendocgia)
        {
            var tendocgiaParameter = tendocgia != null ?
                new ObjectParameter("tendocgia", tendocgia) :
                new ObjectParameter("tendocgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timkiemdocgia_Result>("sp_timkiemdocgia", tendocgiaParameter);
        }
    
        public virtual ObjectResult<string> sp_timkiemsach(Nullable<int> masach)
        {
            var masachParameter = masach.HasValue ?
                new ObjectParameter("masach", masach) :
                new ObjectParameter("masach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_timkiemsach", masachParameter);
        }
    }
}
