//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
            this.PhieuTras = new HashSet<PhieuTra>();
        }
        public DocGia(DocGia dg)
        {
            this.ID = dg.ID;
            this.Email = dg.Email;
            this.HoTen = dg.HoTen;
            this.DiaChi = dg.DiaChi;
            this.NamTotNghiep = dg.NamTotNghiep;
            this.NgayGioiHan = dg.NgayGioiHan;
            this.NgayCapThe = dg.NgayCapThe;
            this.SLuongGioiHan = dg.SLuongGioiHan;
            this.SDT = dg.SDT;
            this.NgayHetHan = dg.NgayHetHan;

        }
    
        public string ID { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string NgayCapThe { get; set; }
        public string NgayHetHan { get; set; }
        public string NamTotNghiep { get; set; }
        public string Email { get; set; }
        public Nullable<double> SLuongGioiHan { get; set; }
        public Nullable<double> NgayGioiHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTra> PhieuTras { get; set; }
    }
}
