//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiThuVienEntities : DbContext
    {
        public QuanLiThuVienEntities()
            : base("name=QuanLiThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DbSet<ChiTietPhieuTra> ChiTietPhieuTras { get; set; }
        public virtual DbSet<DauSach> DauSaches { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<LoaiSach> LoaiSaches { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuTra> PhieuTras { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
    
        public virtual int NhapPhieuMuon(string iD_DocGia, string ngayMuon, string ngaygioihantra)
        {
            var iD_DocGiaParameter = iD_DocGia != null ?
                new ObjectParameter("ID_DocGia", iD_DocGia) :
                new ObjectParameter("ID_DocGia", typeof(string));
    
            var ngayMuonParameter = ngayMuon != null ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(string));
    
            var ngaygioihantraParameter = ngaygioihantra != null ?
                new ObjectParameter("ngaygioihantra", ngaygioihantra) :
                new ObjectParameter("ngaygioihantra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapPhieuMuon", iD_DocGiaParameter, ngayMuonParameter, ngaygioihantraParameter);
        }
    
        public virtual int NhapPhieuTra(string iD_DocGia, string ngayTra)
        {
            var iD_DocGiaParameter = iD_DocGia != null ?
                new ObjectParameter("ID_DocGia", iD_DocGia) :
                new ObjectParameter("ID_DocGia", typeof(string));
    
            var ngayTraParameter = ngayTra != null ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhapPhieuTra", iD_DocGiaParameter, ngayTraParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachSachMuon_Result> sp_DanhSachSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSachMuon_Result>("sp_DanhSachSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongMuon_Result> sp_SoLuongMuon(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongMuon_Result>("sp_SoLuongMuon", ngayParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongSachMuon_Result> sp_SoLuongSachMuon(string ngaybatdau, string ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongSachMuon_Result>("sp_SoLuongSachMuon", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_SoLuongTra_Result> sp_SoLuongTra(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SoLuongTra_Result>("sp_SoLuongTra", ngayParameter);
        }
    
        public virtual ObjectResult<sp_thongtindocgia_Result> sp_thongtindocgia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_thongtindocgia_Result>("sp_thongtindocgia");
        }
    }
}
